# Generated by Django 6.0.7 on 2026-07-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aventurero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('correo', models.EmailField(max_length=60, unique=True, verbose_name='correo electrónico')),
                ('usuario', models.CharField(max_length=60, unique=True, verbose_name='nombre de usuario')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
                ('ultimo_login', models.DateTimeField(auto_now=True, verbose_name='último login')),
                ('is_admin', models.BooleanField(default=False, verbose_name='es administrador')),
                ('is_active', models.BooleanField(default=False, verbose_name='está activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='es staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='es superusuario')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='apellido')),
                ('telefono', models.IntegerField(verbose_name='teléfono')),
                ('bio', models.TextField(blank=True, help_text='Cuénta un poco de ti.', max_length=500, null=True)),
                ('motto', models.CharField(blank=True, help_text='La frase que te define.', max_length=200, null=True)),
                ('profesion', models.CharField(blank=True, max_length=100, null=True, verbose_name='profesión')),
                ('foto', models.ImageField(default='default_imagen.jpg', upload_to='imagenes_perfil', verbose_name='foto')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
