# Generated by Django 6.0.7 on 2026-07-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aventurero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aventurero',
            name='foto',
            field=models.ImageField(default='default_imagen.png', upload_to='imagenes_perfil', verbose_name='foto'),
        ),
    ]
