# Generated by Django 6.0.7 on 2026-07-24 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aventurero', '0002_alter_aventurero_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aventurero',
            name='telefono',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'El teléfono debe tener un máximo de 10 digitos.')], verbose_name='teléfono'),
        ),
    ]
