# Generated by Django 6.0.7 on 2026-07-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='título')),
                ('estado', models.CharField(choices=[('ACTIVO', 'activo'), ('FINALIZADO', 'finalizado'), ('CANCELADO', 'cancelado')], max_length=11, verbose_name='estado')),
                ('descripcion', models.TextField(blank=True, max_length=600, null=True, verbose_name='descripción')),
                ('fecha_inicio', models.DateTimeField(verbose_name='fecha de inicio')),
                ('fecha_termina', models.DateTimeField(verbose_name='fecha de terminación')),
                ('ciudad', models.CharField(max_length=100, verbose_name='ciudad')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='dirección')),
                ('establecimiento', models.CharField(blank=True, max_length=150, null=True, verbose_name='establecimiento')),
                ('foto', models.ImageField(default='experiencia_generica.jpg', upload_to='imagenes_experiencias', verbose_name='foto')),
            ],
        ),
    ]
