# Generated by Django 6.0.7 on 2026-07-30 15:19

import experiencias.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencia',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], max_length=11, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='foto',
            field=models.ImageField(default='experiencia_generica.jpg', help_text='El archivo no puede pesar más de 3.', upload_to='imagenes_experiencias', validators=[experiencias.validators.validar_tamaño_archivo, experiencias.validators.validar_min_dimension, experiencias.validators.validar_max_dimension], verbose_name='foto'),
        ),
    ]
