# Generated by Django 6.0.7 on 2026-07-30 20:05

import experiencias.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiencias', '0002_alter_experiencia_estado_alter_experiencia_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencia',
            name='foto',
            field=models.ImageField(default='experiencia_generica.webp', help_text='El archivo no puede pesar más de 3.', upload_to='imagenes_experiencias', validators=[experiencias.validators.validar_tamaño_archivo, experiencias.validators.validar_min_dimension, experiencias.validators.validar_max_dimension], verbose_name='foto'),
        ),
    ]
