# Generated by Django 6.0.7 on 2026-08-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiencias', '0003_alter_experiencia_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencia',
            name='precio',
            field=models.IntegerField(default=0, max_length=5000000, verbose_name='precio'),
        ),
    ]
