# Generated by Django 6.0.7 on 2026-08-05 15:49

import experiencias.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiencias', '0004_experiencia_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencia',
            name='precio',
            field=models.IntegerField(default=0, validators=[experiencias.validators.validar_precio_maximo], verbose_name='precio'),
        ),
    ]
